### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'cmd'

### ISSUE THREAD

**Issue by tangxiaofeng7** [paradiseduo/ApplicationScanner#10]
Traceback (most recent call last):
  File "/root/ApplicationScanner/lib/apk.py", line 53, in apkScan
    c(filePath).scan()
  File "/root/ApplicationScanner/lib/Android/XSSCheck.py", line 26, in scan
    files = jsBeautify(jsfiles)
  File "/root/ApplicationScanner/lib/tools.py", line 100, in jsBeautify
    runner = RunCMD()
TypeError: __init__() missing 1 required positional argument: 'cmd'

mac和linux都是同样的问题

**Comment by paradiseduo** [comment]
fixed
