### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by fireskyno1** [paradiseduo/ApplicationScanner#11]
Unzip apk atg1609b_99.apk
Finish
Traceback (most recent call last):
  File "/home/ApplicationScanner/lib/apk.py", line 45, in apkScan
    apkInfo(filePath)
  File "/home/ApplicationScanner/lib/apk.py", line 181, in apkInfo
    with open(yml, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ApplicationScanner/atg1609b_99_3OAoqe/apktool.yml'

Clean cache...
Traceback (most recent call last):
  File "./AppScanner.py", line 92, in <module>
    main(sys.argv[1:])
  File "./AppScanner.py", line 70, in main
    apkScan(inputfile, save)
  File "/home/ApplicationScanner/lib/apk.py", line 59, in apkScan
    shutil.rmtree(filePath)
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ApplicationScanner/atg1609b_99_3OAoqe'

**Comment by paradiseduo** [comment]
No such file or directory: '/home/ApplicationScanner/atg1609b_99_3OAoqe/apktool.yml'
看一下apktool能不能把apk解出来，如果解不出来就没法用
