### ISSUE TITLE
能否增加aab格式支持？

### ISSUE THREAD

**Issue by cikichen** [paradiseduo/ApplicationScanner#13]
googleplay只支持aab了

**Comment by paradiseduo** [comment]
给个Demo文件，我研究一下，本质上应该还是个zip

**Comment by cikichen** [comment]
> 给个Demo文件，我研究一下，本质上应该还是个zip

@paradiseduo 
[app-release.zip](https://github.com/paradiseduo/ApplicationScanner/files/10576069/app-release.zip)

把ho后缀改成aab
<img width="140" alt="image" src="https://user-images.githubusercontent.com/1478821/216526819-81a2a613-906f-4f47-b46d-1a0f5da30538.png">

**Comment by paradiseduo** [comment]
这个文件有点问题。。
bundletool.jar 提示无法转成apks
```
[BT:1.14.0] Error: The archive doesn't seem to be an App Bundle, it is missing required file 'BundleConfig.pb'.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: The archive doesn't seem to be an App Bundle, it is missing required file 'BundleConfig.pb'.
	at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.checkBundleHasBundleConfig(MandatoryFilesPresenceValidator.java:73)
	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.validateBundleZipFile(MandatoryFilesPresenceValidator.java:60)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundleZipFile$0(ValidatorRunner.java:42)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleZipFile(ValidatorRunner.java:42)
	at com.android.tools.build.bundletool.validation.AppBundleValidator.validateFile(AppBundleValidator.java:100)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:901)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:83)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
```

**Comment by cikichen** [comment]
[file.zip](https://github.com/paradiseduo/ApplicationScanner/files/10577007/file.zip)
直接解压
@paradiseduo

**Comment by paradiseduo** [comment]
d8d95d51f93a01a58986ca159f9427614c5bb4a1
