### ISSUE TITLE
解析报错

### ISSUE THREAD

**Issue by like4h** [paradiseduo/ApplicationScanner#14]
- 执行命令：

(apkana) python AppScanner.py -i test.apk

- 报错内容如下：

Unzip apk test.apk
Finish
Traceback (most recent call last):
  File "/root/apkana/ApplicationScanner/lib/apk.py", line 59, in apkScan
    apkInfo(filePath)
  File "/root/apkana/ApplicationScanner/lib/apk.py", line 195, in apkInfo
    with open(yml, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/apkana/ApplicationScanner/test_3E2Tdu/apktool.yml'

Clean cache...
Traceback (most recent call last):
  File "/root/apkana/ApplicationScanner/AppScanner.py", line 92, in <module>
    main(sys.argv[1:])
  File "/root/apkana/ApplicationScanner/AppScanner.py", line 70, in main
    apkScan(inputfile, save)
  File "/root/apkana/ApplicationScanner/lib/apk.py", line 73, in apkScan
    shutil.rmtree(filePath)
  File "/root/anaconda3/envs/apkana/lib/python3.9/shutil.py", line 706, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/root/anaconda3/envs/apkana/lib/python3.9/shutil.py", line 704, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/root/apkana/ApplicationScanner/test_3E2Tdu'
(apkana)

- 尝试解决方法：

使用绝对路径，结果还是一样的报错

**Comment by like4h** [comment]
ok thanks i know this problem.
