### ISSUE TITLE
flutter 项目编译的ipa 包报错

### ISSUE THREAD

**Issue by linglong117** [paradiseduo/ApplicationScanner#20]
Traceback (most recent call last):
  File "/Users/xx/security/ApplicationScannerx/lib/ipa.py", line 54, in ipaScan
    process_app_info_and_binaries(appInfoPath, appBinPath, filePath)
  File "/Users/xx/security/ApplicationScannerx/lib/ipa.py", line 65, in process_app_info_and_binaries
    iOSInfo(appInfoPath)
  File "/Users/xx/security/ApplicationScannerx/lib/ipa.py", line 122, in iOSInfo
    get_value('CFBundleDisplayName') + pl['CFBundleDisplayName'],
KeyError: 'CFBundleDisplayName'

非flutter 的项目，可以扫描

**Comment by paradiseduo** [comment]
我这边用Flutter项目试了，没问题啊，看报错是没给应用命名，你应该直接用的Demo工程吧，Xcode里给APP加个名字
