### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MrBe1ieVe** [paradiseduo/ApplicationScanner#8]
```
Traceback (most recent call last):
  File "/SDK 安全扫描/ApplicationScanner/lib/apk.py", line 47, in apkScan
    apkInfo(filePath)
  File "/SDK 安全扫描/ApplicationScanner/lib/apk.py", line 139, in apkInfo
    with open(yml, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory:'/SDK 安全扫描/ApplicationScanner/test_xc6GQp/apktool.yml'
```

## 原因
路径中存在空格，部分未使用引号包裹路径导致不能正常解析。

## 解决办法
去掉文件夹中空格即可解决

## 相关代码

/lib/apk.py 41行
`strline = f'java -jar {apktool} d -f {inputfile} -o {filePath} --only-main-classes'`

/lib/ipa.py 128行起
`strline1 = 'strings -a -T Mach-O ' + appBinPath + " > " + stringDumpPath`

**Comment by paradiseduo** [comment]
now fix
